---

- hosts: all
  become: true
  tasks:

# Ubuntu
  - name: Playbook is installing apache2 and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# Rocky
  - name: Playbook is installing apache2 and php packages for Rocky
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"
