---

- hosts: all
  become: true
  tasks:

# Ubuntu
  - name: Playbook is installing apache2 and php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
