---

- hosts: all
  become: true
  tasks:

  - name: Playbook is updating cached repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Playbook is installing apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Playbook is installing PHP support for Apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

#

  - name: Playbook is updating cached repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: Playbook is installing apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Playbook is installing PHP support for Apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Rocky"
