---

- hosts: all
  become: true
  tasks:

  - name: Playbook is updating cached repository index
    apt:
      update_cache: yes

  - name: Playbook is removing apahe2 package
    apt:
      name: apache2
      state: absent

  - name: Playbook is removing PHP support for Apahe
    apt:
      name: libapache2-mod-php
      state: absent
