---
# ALL
- hosts: all
  become: true
  pre_tasks:

# Ubuntu
  - name: Playbook is installing Updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# Rocky
  - name: Playbook is installing Updates (Rocky)
    tags: always
    dnf:
      update_only: yes 
      update_cache: yes
    when: ansible_distribution == "Rocky"

# WEB SERVERS
- hosts: web_servers
  become: true
  tasks:

# Ubuntu
  - name: Playbook is installing apache2 and php packages (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# Rocky
  - name: Playbook is installing apache2 and php packages (Rocky)
    tags: apache,rocky,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"

# Copy default_site html file over
  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

# DB SERVERS
- hosts: db_servers
  become: true
  tasks:

  - name: Playbook is installing mariadb package (Rocky)
    tags: rocky,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: Playbook is installing mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

# FILE SERVERS
- hosts: file_servers
  become: true
  tasks:

  - name: Playbook is installing samba package
    tags: samba
    package:
      name: samba
      state: latest
